import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import Script from "next/script";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

// UI刷新案の指定フォント。JP グリフを含むため subsets はプリロード対象の latin のみ、
// 日本語のプリロードは無効化（ビルド警告と過剰なプリロードを避ける）。
const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
  variable: "--font-noto-sans-jp",
  display: "swap",
  preload: false,
});

export const metadata: Metadata = {
  title: "ABS EMS",
  description: "Generated by Logicode",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  //プリズマで使うよう？　上のRootLayoutにasyncを追記する
  //const user = await db.user.findMany

  return (
    // refetchOnWindowFocus はデフォルト有効だが、タブ復帰のたびに /api/auth/session への
    // 往復（Worker 起動＋DBアクセス）が発生するため無効化。セッション情報は表示用途のみ。
    <SessionProvider session={session} refetchOnWindowFocus={false}>
      <html lang="ja" className={notoSansJP.variable}>
        {/* headタグとその中にアイコンやテーマカラー、manifestを記述する */}
        <head>
          <link rel="manifest" href="/manifest.json" />
          <meta name="theme-color" content="#10243E" />
        </head>
        <body className={notoSansJP.className}>
          <Toaster />
          {children}
          {/* Cloudflare Web Analytics（旧 Vercel Speed Insights の代替）。
              token は全訪問者に配る公開値（forgeonics.com ゾーン連携サイトのもの。
              ホスト名手入力で作ったサイトの token は ingest 側で有効化されず 503 になる）。
              beacon は SPA のルート遷移も自動計測する。next dev では読み込まない。 */}
          {process.env.NODE_ENV === "production" && (
            <Script
              strategy="afterInteractive"
              src="https://static.cloudflareinsights.com/beacon.min.js"
              data-cf-beacon='{"token": "d7af9ef8eb544c439b12d40727bbaa74"}'
            />
          )}
        </body>
      </html>
    </SessionProvider>
  );
}
