import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import Script from "next/script";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ChakraProvider } from '@chakra-ui/react'

// UI刷新案の指定フォント。JP グリフを含むため subsets はプリロード対象の latin のみ、
// 日本語のプリロードは無効化（ビルド警告と過剰なプリロードを避ける）。
const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
  variable: "--font-noto-sans-jp",
  display: "swap",
  preload: false,
});

export const metadata: Metadata = {
  title: "ABS EMS",
  description: "Generated by Logicode",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  //プリズマで使うよう？　上のRootLayoutにasyncを追記する
  //const user = await db.user.findMany

  return (
    <SessionProvider session={session}>
      <html lang="ja" className={notoSansJP.variable}>
        {/* headタグとその中にアイコンやテーマカラー、manifestを記述する */}
        <head>
          <link rel="manifest" href="/manifest.json" />
          <meta name="theme-color" content="#10243E" />
        </head>
        <body className={notoSansJP.className}>
          <Toaster />
          <ChakraProvider>{children}</ChakraProvider>
          {/* Cloudflare Web Analytics（旧 Vercel Speed Insights の代替）。
              token は全訪問者に配る公開値（ダッシュボードのサイト設定と対応）。
              beacon は SPA のルート遷移も自動計測する。next dev では読み込まない。 */}
          {process.env.NODE_ENV === "production" && (
            <Script
              strategy="afterInteractive"
              src="https://static.cloudflareinsights.com/beacon.min.js"
              data-cf-beacon='{"token": "511cfa581a144ba7bba2ec62e4d2271e"}'
            />
          )}
        </body>
      </html>
    </SessionProvider>
  );
}
